{% set name = "pyaedt" %}
{% set version = "0.6.54" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyaedt-{{ version }}.tar.gz
  sha256: bf4d53717c4ec873f5167998d4a9e4ff28a5eb96024d33244491bd5eb8e25a40

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]

  host:
    - pip
    - python

  run:
    - python
    - mono  # [linux]
    - dotnet-aspnetcore ==3.1.23  # [linux]
    - cffi ==1.15.0  # [linux]
    - pywin32 >=303  # [win]
    - pythonnet ==3.0.0.post1
    - rpyc ==5.0.1
    - pyvista >=0.34.1
    - numpy
    - matplotlib-base
    - psutil
    - pandas

test:
  imports:
    - pyaedt

about:
  home: https://pypi.org/project/pyaedt/
  summary: Higher-Level Pythonic Ansys Electronics Desktop Framework
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
  doc_url: https://aedt.docs.pyansys.com/
  dev_url: https://github.com/pyansys/pyaedt

extra:
  recipe-maintainers:
    - MaxJPRey
    - maxcapodi78
    - Samuelopez-ansys
